# crypto-app export columns
UTC_TIME_COLUMN = "UTC_Time"
OPERATION_COLUMN = "Operation"
DESCRIPTION_COLUMN = "Description"
DATA_COLUMN = "Data"

# crypto-app export operations
TRANSACTION_OPERATION = "Transaction"
TRANSFER_OPERATION = "Transfer"
EARN_OPERATION = "Earn"

# binance operations
BINANCE_BUY_OPERATION = "Buy"
BINANCE_TRANSACTION_RELATED_OPERATION = "Transaction Related"
BINANCE_FEE_OPERATION = "Fee"
BINANCE_DEPOSIT_OPERATION = "Deposit"
BINANCE_WITHDRAWAL_OPERATION = "Withdrawal"
BINANCE_TRANSACTION_OPERATION = "Transaction"
BINANCE_TRANSFER_OPERATION = "Transfer"
BINANCE_EARN_OPERATION = "Earn"
BINANCE_POS_SAVINGS_INTEREST_OPERATION = "POS savings interest"
BINANCE_SAVINGS_INTEREST_OPERATION = "Savings Interest"
BINANCE_ETH_STAKING_REWARDS_OPERATION = "ETH 2.0 Staking Rewards"
BINANCE_ETH_STAKING_TRANSACTION_OPERATION = "ETH 2.0 Staking"
BINANCE_SMALL_ASSETS_EXCHANGE_BNB_OPERATION = "Small assets exchange BNB"
BINANCE_OTC_TRADING_OPERATION = "Large OTC trading"
BINANCE_COMMISSION_FEE_OPERATION = "Commission Fee Shared With You"
BINANCE_COMMISION_HISTORY_OPERATION = "Commission History"
BINANCE_REFERRAL_KICKBACK_OPERATION = "Referral Kickback"

# binance description
BINANCE_DEPOSIT_DESCRIPTION = "Binance deposit"
BINANCE_WITHDRAWAL_DESCRIPTION = "Binance withdrawal"
BINANCE_TRANSACTION_DESCRIPTION = "Binance transaction"
BINANCE_EARN_DESCRIPTION = "Binance earn"

# binance export columns
BINANCE_UTC_TIME_COLUMN = "UTC_Time"
BINANCE_OPERATION_COLUMN = "Operation"
BINANCE_DESCRIPTION_COLUMN = "Description"
BINANCE_DATA_COLUMN = "Data"
BINANCE_COIN_COLUMN = "Coin"
BINANCE_CHANGE_COLUMN = "Change"
