# crypto-app export columns
UTC_TIME_COLUMN = "UTC_Time"
OPERATION_COLUMN = "Operation"
DESCRIPTION_COLUMN = "Description"
DATA_COLUMN = "Data"

CRYPTO_APP_EXPORT_COLUMNS = [
    UTC_TIME_COLUMN,
    OPERATION_COLUMN,
    DESCRIPTION_COLUMN,
    DATA_COLUMN,
]

# crypto-app export operations
TRANSACTION_OPERATION = "Transaction"
TRANSFER_OPERATION = "Transfer"
EARN_OPERATION = "Earn"

# crypto-app dir names
BINANCE_DIR = "\\binance"
KRAKEN_DIR = "\\kraken"
BTC_DIR = "\\btc"
ETH_DIR = "\\eth"
DOT_DIR = "\\dot"
SOL_DIR = "\\sol"

# binance export columns
BINANCE_UTC_TIME_COLUMN = "UTC_Time"
BINANCE_OPERATION_COLUMN = "Operation"
BINANCE_DESCRIPTION_COLUMN = "Description"
BINANCE_DATA_COLUMN = "Data"
BINANCE_COIN_COLUMN = "Coin"
BINANCE_CHANGE_COLUMN = "Change"

# binance operations
BINANCE_BUY_OPERATION = "Buy"
BINANCE_TRANSACTION_RELATED_OPERATION = "Transaction Related"
BINANCE_FEE_OPERATION = "Fee"
BINANCE_DEPOSIT_OPERATION = "Deposit"
BINANCE_WITHDRAWAL_OPERATION = "Withdrawal"
BINANCE_TRANSACTION_OPERATION = "Transaction"
BINANCE_TRANSFER_OPERATION = "Transfer"
BINANCE_EARN_OPERATION = "Earn"
BINANCE_POS_SAVINGS_INTEREST_OPERATION = "POS savings interest"
BINANCE_POS_SAVINGS_PURCHASE_OPERATION = "POS savings purchase"
BINANCE_POS_SAVINGS_REDEMPTION_OPERATION = "POS savings redemption"
BINANCE_SAVINGS_INTEREST_OPERATION = "Savings Interest"
BINANCE_SAVINGS_PURCHASE_OPERATION = "Savings purchase"
BINANCE_SAVINGS_PRINCIPAL_REDEMPTION_OPERATION = "Savings Principal redemption"
BINANCE_ETH_STAKING_REWARDS_OPERATION = "ETH 2.0 Staking Rewards"
BINANCE_ETH_STAKING_TRANSACTION_OPERATION = "ETH 2.0 Staking"
BINANCE_SMALL_ASSETS_EXCHANGE_BNB_OPERATION = "Small assets exchange BNB"
BINANCE_OTC_TRADING_OPERATION = "Large OTC trading"
BINANCE_COMMISSION_FEE_OPERATION = "Commission Fee Shared With You"
BINANCE_COMMISION_HISTORY_OPERATION = "Commission History"
BINANCE_REFERRAL_KICKBACK_OPERATION = "Referral Kickback"

# binance description
BINANCE_DEPOSIT_DESCRIPTION = "Binance deposit"
BINANCE_WITHDRAWAL_DESCRIPTION = "Binance withdrawal"
BINANCE_TRANSACTION_DESCRIPTION = "Binance transaction"
BINANCE_EARN_DESCRIPTION = "Binance earn"

# kraken export columns
KRAKEN_REFID_COLUMN = "refid"
KRAKEN_UTC_TIME_COLUMN = "time"
KRAKEN_TYPE_COLUMN = "type"
KRAKEN_SUBTYPE_COLUMN = "subtype"
KRAKEN_ASSET_COLUMN = "asset"
KRAKEN_AMOUNT_COLUMN = "amount"
KRAKEN_FEE_COLUMN = "fee"
KRAKEN_BALANCE_COLUMN = "balance"

# kraken types
KRAKEN_DEPOSIT_TYPE = "deposit"
KRAKEN_STAKING_TYPE = "staking"
KRAKEN_TRADE_TYPE = "trade"
KRAKEN_TRANSFER_TYPE = "transfer"
KRAKEN_WITHDRAWAL_TYPE = "withdrawal"

# kraken subtypes
KRAKEN_SPOT_TO_STAKING_SUBTYPE = "spottostaking"

# kraken description
KRAKEN_EARN_DESCRIPTION = "Kraken earn"
KRAKEN_TRANSACTION_DESCRIPTION = "Kraken transaction"
KRAKEN_TRANSFER_DESCRIPTION = "Kraken transfer"

# solana export columns
SOLANA_UTC_TIME_COLUMN = "timestamp"
SOLANA_TX_TYPE_COLUMN = "tx_type"
SOLANA_RECEIVED_AMOUNT = "received_amount"
SOLANA_RECEIVED_CURRENCY_COLUMN = "received_currency"
SOLANA_SENT_AMOUNT_COLUMN = "sent_amount"
SOLANA_SENT_CURRENCY_COLUMN = "sent_currency"
SOLANA_FEE_COLUMN = "fee"
SOLANA_FEE_CURRENCY_COLUMN = "fee_currency"
SOLANA_COMMENT_COLUMN = "comment"

# solana types
SOLANA_STAKING_TYPE = "STAKING"
SOLANA_SPEND_TYPE = "SPEND"
SOLANA_TRANSFER_TYPE = "TRANSFER"

# solana description
SOLANA_EARN_DESCRIPTION = "Solana earn"
SOLANA_SPEND_DESCRIPTION = "Solana spend"
SOLANA_TRANSFER_DESCRIPTION = "Solana transfer"
