# crypto-app export columns
UTC_TIME_COLUMN = "UTC_Time"
OPERATION_COLUMN = "Operation"
DESCRIPTION_COLUMN = "Description"
DATA_COLUMN = "Data"

CRYPTO_APP_EXPORT_COLUMNS = [
    UTC_TIME_COLUMN,
    OPERATION_COLUMN,
    DESCRIPTION_COLUMN,
    DATA_COLUMN,
]

# crypto-app export operations
TRANSACTION_OPERATION = "Transaction"
TRANSFER_OPERATION = "Transfer"
EARN_OPERATION = "Earn"

# crypto-app dir names
BINANCE_DIR_PATH = "\\binance"
BINANCE_TRANSACTION_EXPORT_NAME = "transaction"
BINANCE_EARNING_EXPORT_NAME = "earning"
BINANCE_WITHDRAWAL_EXPORT_NAME = "withdrawal"
KRAKEN_DIR_PATH = "\\kraken"
BTC_DIR_PATH = "\\btc"
ETH_DIR_PATH = "\\eth"
DOT_DIR_PATH = "\\dot"
SOL_DIR_PATH = "\\sol"

# binance export columns
BINANCE_UTC_TIME_COLUMN = "UTC_Time"
BINANCE_OPERATION_COLUMN = "Operation"
BINANCE_DESCRIPTION_COLUMN = "Description"
BINANCE_DATA_COLUMN = "Data"
BINANCE_COIN_COLUMN = "Coin"
BINANCE_CHANGE_COLUMN = "Change"

# binance withdrawal export columns
BINANCE_WITHDRAWAL_UTC_TIME_COLUMM = "Date(UTC)"
BINANCE_WITHDRAWAL_COIN_COLUMM = "Coin"
BINANCE_WITHDRAWAL_TRANSACTION_FEE_COLUMM = "TransactionFee"

# binance transaction export columns
BINANCE_TRANSACTION_UTC_TIME_COLUMM = "Date(UTC)"
BINANCE_TRANSACTION_PAIR_COLUMM = "Pair"
BINANCE_TRANSACTION_SIDE_COLUMM = "Side"
BINANCE_TRANSACTION_EXECUTED_COLUMM = "Executed"
BINANCE_TRANSACTION_AMOUNT_COLUMM = "Amount"
BINANCE_TRANSACTION_FEE_COLUMM = "Fee"

# binance transaction export values
BINANCE_TRANSACTION_SIDE_BUY_VALUE = "BUY"
BINANCE_TRANSACTION_SIDE_SELL_VALUE = "SELL"

# binance operations
BINANCE_BUY_OPERATION = "Buy"
BINANCE_TRANSACTION_RELATED_OPERATION = "Transaction Related"
BINANCE_FEE_OPERATION = "Fee"
BINANCE_DEPOSIT_OPERATION = "Deposit"
BINANCE_FIAT_DEPOSIT_OPERATION = "Fiat Deposit"
BINANCE_WITHDRAWAL_OPERATION = "Withdraw"
BINANCE_TRANSACTION_OPERATION = "Transaction"
BINANCE_DISTRIBUTION_OPERATION = "Distribution"
BINANCE_DOT_SLOT_AUCTION_REWARDS = "DOT Slot Auction Rewards"
BINANCE_STAKING_REWARDS_OPERATION = "Staking Rewards"
BINANCE_STAKING_PURCHASE_OPERATION = "Staking Purchase"
BINANCE_STAKING_REDEMPTION_OPERATION = "Staking Redemption"
BINANCE_SIMPLE_EARN_FLEXIBLE_INTEREST_OPERATION = "Simple Earn Flexible Interest"
BINANCE_SAVINGS_DISTRIBUTION_OPERATION = "Savings Distribution"
BINANCE_POS_SAVINGS_INTEREST_OPERATION = "POS savings interest"
BINANCE_POS_SAVINGS_PURCHASE_OPERATION = "POS savings purchase"
BINANCE_SIMPLE_EARN_FLEXIBLE_SUBSCRIPTION_OPERATION = (
    "Simple Earn Flexible Subscription"
)
BINANCE_SIMPLE_EARN_FLEXIBLE_REDEMPTION_OPERATION = "Simple Earn Flexible Redemption"
BINANCE_SIMPLE_EARN_LOCKED_REWARDS_OPERATION = "Simple Earn Locked Rewards"
BINANCE_SIMPLE_EARN_LOCKED_SUBSCRIPTION_OPERATION = "Simple Earn Locked Subscription"
BINANCE_SIMPLE_EARN_LOCKED_REDEMPTION_OPERATION = "Simple Earn Locked Redemption"
BINANCE_POS_SAVINGS_REDEMPTION_OPERATION = "POS savings redemption"
BINANCE_SAVINGS_INTEREST_OPERATION = "Savings Interest"
BINANCE_SAVINGS_PURCHASE_OPERATION = "Savings purchase"
BINANCE_SAVINGS_PRINCIPAL_REDEMPTION_OPERATION = "Savings Principal redemption"
BINANCE_ETH_STAKING_REWARDS_OPERATION = "ETH 2.0 Staking Rewards"
BINANCE_ETH_STAKING_TRANSACTION_OPERATION = "ETH 2.0 Staking"

# binance description
BINANCE_DEPOSIT_DESCRIPTION = "Binance deposit"
BINANCE_WITHDRAWAL_DESCRIPTION = "Binance withdrawal"
BINANCE_TRANSACTION_DESCRIPTION = "Binance transaction"
BINANCE_EARN_DESCRIPTION = "Binance earn"

# kraken export columns
KRAKEN_TXID_COLUMN = "txid"
KRAKEN_REFID_COLUMN = "refid"
KRAKEN_UTC_TIME_COLUMN = "time"
KRAKEN_TYPE_COLUMN = "type"
KRAKEN_SUBTYPE_COLUMN = "subtype"
KRAKEN_ASSET_COLUMN = "asset"
KRAKEN_AMOUNT_COLUMN = "amount"
KRAKEN_FEE_COLUMN = "fee"
KRAKEN_BALANCE_COLUMN = "balance"

# kraken types
KRAKEN_DEPOSIT_TYPE = "deposit"
KRAKEN_STAKING_TYPE = "staking"
KRAKEN_TRADE_TYPE = "trade"
KRAKEN_TRANSFER_TYPE = "transfer"
KRAKEN_WITHDRAWAL_TYPE = "withdrawal"

# kraken subtypes
KRAKEN_SPOT_TO_STAKING_SUBTYPE = "spottostaking"

# kraken description
KRAKEN_EARN_DESCRIPTION = "Kraken earn"
KRAKEN_TRANSACTION_DESCRIPTION = "Kraken transaction"
KRAKEN_TRANSFER_DESCRIPTION = "Kraken transfer"

# solana export columns
SOLANA_UTC_TIME_COLUMN = "timestamp"
SOLANA_TX_TYPE_COLUMN = "tx_type"
SOLANA_RECEIVED_AMOUNT = "received_amount"
SOLANA_RECEIVED_CURRENCY_COLUMN = "received_currency"
SOLANA_SENT_AMOUNT_COLUMN = "sent_amount"
SOLANA_SENT_CURRENCY_COLUMN = "sent_currency"
SOLANA_FEE_COLUMN = "fee"
SOLANA_FEE_CURRENCY_COLUMN = "fee_currency"
SOLANA_COMMENT_COLUMN = "comment"

# solana types
SOLANA_STAKING_TYPE = "STAKING"
SOLANA_SPEND_TYPE = "SPEND"
SOLANA_TRANSFER_TYPE = "TRANSFER"

# solana description
SOLANA_EARN_DESCRIPTION = "Solana earn"
SOLANA_SPEND_DESCRIPTION = "Solana spend"
SOLANA_TRANSFER_DESCRIPTION = "Solana transfer"

# polkadot export columns
POLKADOT_UTC_TIME_COLUMN = "Date"
POLKADOT_EXTRINSIC_ID_COLUMN = "Extrinsic ID"
POLKADOT_ACTION_COLUMN = "Action"

# polkadot actions
POLKADOT_JOIN_NOMINATION_POOLS_ACTION = "nominationpools(join)"
POLKADOT_BOND_EXTRA_NOMINATION_POOLS_ACTION = "nominationpools(bond_extra)"

# polkadot description
POLKADOT_EARN_DESCRIPTION = "Polkadot earn"
POLKADOT_SPEND_DESCRIPTION = "Polkadot spend"
POLKADOT_TRANSFER_DESCRIPTION = "Polkadot transfer"
